name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Det här betyder att deployment sker på push till "main" branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Steg 1: Check out repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Steg 2: Installera Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Steg 3: Installera projektets beroenden
      - name: Install dependencies
        run: npm install

      # Steg 4: Bygg appen
      - name: Build the app
        run: npm run build

      # Steg 5: Deploy till GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          npm install gh-pages --save-dev
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
